server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chbcnonprod
    username: root
    password:

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: repository-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/